# Site settings
title: Lokmont
description: Lokmont is a responsive simple theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lokmont-jekyll.netlify.com/" # the base hostname & protocol for your site, e.g. http://example.com

repository: github_username/github_username.github.io
github_url: https://github.com/github_username
url: https://github_username.github.io
