# Site settings
title: Pisces
description: simple theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
repository: "xiaomo1q/PrimitivePisces"
github_url: "https://github.com/xiaomo1q"
url: "https://xiaomo1q.github.io/PrimitivePisces/"
